#!/usr/bin/env bash
# The bash script installs nginx and configures it on a remote server.
# And serves a default page index.html on the HTTP GET request.

sudo apt-get update -y

sudo apt-get install nginx -y

echo 'Hello World!' > /var/www/html/index.html

service nginx restart
