#!/usr/bin/env bash
# Script configures an Nginx server to listen on port 80 of all the servers active IPv4 IPs.

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
