#!/usr/bin/env bash
# Script configures an Nginx server to listen on port 80 of all serevers active IPv4 IPs.
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
kill "$(pgrep 'nginx' | head -1)"
