#!/usr/bin/env bash
# Displays "Best School" 10 times using the while loop,
  on the 9th iteration, say Hi on a new line.

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  ((count++))
done
